services:
  totalsegmentator-restful-api:
    restart: always
    image: mariohuang/totalsegmentator-restful-api:1.1.0
    ports:
      - "8001:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
